#!/bin/bash
set -euo pipefail

if [[ -z "${BASH_VERSION:-}" ]]; then
  echo "Please run this script with bash." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

TASK_SCRIPT="${SCRIPT_DIR}/evaluate_composable_toxicity_case_study_task.sh"

PYTHON_BIN="${PYTHON_BIN:-/opt/conda/bin/python}"
BASE_MODEL="${BASE_MODEL:-models/llama3-8b/snapshots/8cde5ca8380496c9a6cc7ef3a8b46a0372a1d920}"
SPEC1="${SPEC1:-multi_train/trainer_output/Llama3-8b-Loreft_truthful_4/checkpoint-3330/intervenable_model}"
SPEC2="${SPEC2:-multi_train/trainer_output/Llama3-8b-Loreft_moral/checkpoint-330/intervenable_model}"
SPEC3="${SPEC3:-multi_train/trainer_output/Llama3-8b-Loreft_stereotype_1/checkpoint-160/intervenable_model}"
SPEC4="${SPEC4:-multi_train/trainer_output/Llama3-8b-Loreft_toxicity/checkpoint-235/intervenable_model}"

SCORE_STATS_PATH="${SCORE_STATS_PATH:-multi_train/calibration/train_input/stats/intervention_stats_specialist_train_input.json}"
SCORE_SOURCE="${SCORE_SOURCE:-intervention_norm}"
SCORE_NORMALIZER="${SCORE_NORMALIZER:-log_zscore}"
COMPOSITION_METHOD="${COMPOSITION_METHOD:-compat_filtered_topk}"
COMPOSE_DOMAIN="${COMPOSE_DOMAIN:-output}"
COMPOSITION_TEMPERATURE="${COMPOSITION_TEMPERATURE:-1.0}"
COMPOSITION_TOPK="${COMPOSITION_TOPK:-2}"
COMPAT_THRESHOLD="${COMPAT_THRESHOLD:-0.0}"
TARGET_LAYERS="${TARGET_LAYERS:--1}"
ENABLE_DEBUG_CACHE="${ENABLE_DEBUG_CACHE:-1}"

TASK="${TASK:-toxicity}"
GPU_IDS_VALUE="${GPU_IDS:-0}"
RUN_TS="${RUN_TS:-$(date +%Y%m%d_%H%M%S)}"
LOG_DIR="${LOG_DIR:-multi_train/logs/composable_toxicity_case_study_${RUN_TS}}"
SUMMARY_DIR="${SUMMARY_DIR:-multi_train/eval_router/summaries}"
MERGE_SUMMARY_PATH="${MERGE_SUMMARY_PATH:-}"
TOXICITY_SAMPLE_MODE="${TOXICITY_SAMPLE_MODE:-random}"
TOXICITY_SAMPLE_SEED="${TOXICITY_SAMPLE_SEED:-42}"
TOXICITY_MECHANISM_TRACE="${TOXICITY_MECHANISM_TRACE:-1}"
TOXICITY_MECHANISM_TRACE_OUTPUT="${TOXICITY_MECHANISM_TRACE_OUTPUT:-}"

mkdir -p "${LOG_DIR}"
mkdir -p "${SUMMARY_DIR}"

SUMMARY_PREFIX="${MERGE_SUMMARY_PATH:-composable-toxicity-case-study}"
MERGE_SUMMARY_FILE="${SUMMARY_DIR}/${SUMMARY_PREFIX}_${RUN_TS}_merge_summary.json"

echo "PYTHON_BIN=${PYTHON_BIN}"
echo "BASE_MODEL=${BASE_MODEL}"
echo "SPEC1=${SPEC1}"
echo "SPEC2=${SPEC2}"
echo "SPEC3=${SPEC3}"
echo "SPEC4=${SPEC4}"
echo "SCORE_STATS_PATH=${SCORE_STATS_PATH}"
echo "SCORE_SOURCE=${SCORE_SOURCE}"
echo "SCORE_NORMALIZER=${SCORE_NORMALIZER}"
echo "COMPOSITION_METHOD=${COMPOSITION_METHOD}"
echo "COMPOSE_DOMAIN=${COMPOSE_DOMAIN}"
echo "COMPOSITION_TEMPERATURE=${COMPOSITION_TEMPERATURE}"
echo "COMPOSITION_TOPK=${COMPOSITION_TOPK}"
echo "COMPAT_THRESHOLD=${COMPAT_THRESHOLD}"
echo "TARGET_LAYERS=${TARGET_LAYERS}"
echo "ENABLE_DEBUG_CACHE=${ENABLE_DEBUG_CACHE}"
echo "TASK=${TASK}"
echo "GPU_IDS=${GPU_IDS_VALUE}"
echo "RUN_TS=${RUN_TS}"
echo "LOG_DIR=${LOG_DIR}"

GPU_IDS_ARR=()
read -r -a GPU_IDS_ARR <<< "${GPU_IDS_VALUE}"
GPU_ID="${GPU_IDS_ARR[0]:-0}"

SUMMARY_PATH="${SUMMARY_DIR}/${SUMMARY_PREFIX}_${RUN_TS}.json"
LOG_FILE="${LOG_DIR}/toxicity.log"

{
  echo "===== toxicity ====="
  echo "TASK=${TASK}"
  echo "GPU=cuda:${GPU_ID}"
  echo "SUMMARY_PATH=${SUMMARY_PATH}"
  echo "TOXICITY_SAMPLE_MODE=${TOXICITY_SAMPLE_MODE}"
  echo "TOXICITY_SAMPLE_SEED=${TOXICITY_SAMPLE_SEED}"
  echo "TOXICITY_MECHANISM_TRACE=${TOXICITY_MECHANISM_TRACE}"
  echo "TOXICITY_MECHANISM_TRACE_OUTPUT=${TOXICITY_MECHANISM_TRACE_OUTPUT}"
  echo
  env \
    PYTHON_BIN="${PYTHON_BIN}" \
    TASK="${TASK}" \
    BASE_MODEL="${BASE_MODEL}" \
    SPEC1="${SPEC1}" \
    SPEC2="${SPEC2}" \
    SPEC3="${SPEC3}" \
    SPEC4="${SPEC4}" \
    SCORE_STATS_PATH="${SCORE_STATS_PATH}" \
    SCORE_SOURCE="${SCORE_SOURCE}" \
    SCORE_NORMALIZER="${SCORE_NORMALIZER}" \
    COMPOSITION_METHOD="${COMPOSITION_METHOD}" \
    COMPOSE_DOMAIN="${COMPOSE_DOMAIN}" \
    COMPOSITION_TEMPERATURE="${COMPOSITION_TEMPERATURE}" \
    COMPOSITION_TOPK="${COMPOSITION_TOPK}" \
    COMPAT_THRESHOLD="${COMPAT_THRESHOLD}" \
    TARGET_LAYERS="${TARGET_LAYERS}" \
    ENABLE_DEBUG_CACHE="${ENABLE_DEBUG_CACHE}" \
    SUMMARY_PATH="${SUMMARY_PATH}" \
    LOG_DIR="${LOG_DIR}" \
    DATASETS="${DATASETS:-toxic nontoxic}" \
    PROMPTS="${PROMPTS:-benign adversarial}" \
    DATASET_ROOT="${DATASET_ROOT:-multi_train/eval_toxicity/data/user_prompts}" \
    MAX_SAMPLES="${MAX_SAMPLES:-200}" \
    TOXICITY_SAMPLE_MODE="${TOXICITY_SAMPLE_MODE}" \
    TOXICITY_SAMPLE_SEED="${TOXICITY_SAMPLE_SEED}" \
    TOXICITY_MECHANISM_TRACE="${TOXICITY_MECHANISM_TRACE}" \
    TOXICITY_MECHANISM_TRACE_OUTPUT="${TOXICITY_MECHANISM_TRACE_OUTPUT}" \
    TOXICITY_BATCH_SIZE="${TOXICITY_BATCH_SIZE:-8}" \
    TOXICITY_POSITIONS="${TOXICITY_POSITIONS:-11}" \
    TOXICITY_GREEDY_DECODING="${TOXICITY_GREEDY_DECODING:-0}" \
    TOXICITY_DATASETS="${TOXICITY_DATASETS:-toxic nontoxic}" \
    TOXICITY_PROMPTS="${TOXICITY_PROMPTS:-benign adversarial}" \
    TOXICITY_DATASET_ROOT="${TOXICITY_DATASET_ROOT:-multi_train/eval_toxicity/data/user_prompts}" \
    TOXICITY_MAX_SAMPLES="${TOXICITY_MAX_SAMPLES:-200}" \
    TOXICITY_N_GENERATIONS="${TOXICITY_N_GENERATIONS:-5}" \
    TOXICITY_MAX_TOKENS="${TOXICITY_MAX_TOKENS:-50}" \
    TOXICITY_TEMPERATURE="${TOXICITY_TEMPERATURE:-0.7}" \
    TOXICITY_RUN_ANALYSIS="${TOXICITY_RUN_ANALYSIS:-1}" \
    TOXICITY_ANALYSIS_BATCH_SIZE="${TOXICITY_ANALYSIS_BATCH_SIZE:-16}" \
    TOXICITY_DETOXIFY_MODEL="${TOXICITY_DETOXIFY_MODEL:-original}" \
    TOXICITY_ANALYSIS_DEVICE="${TOXICITY_ANALYSIS_DEVICE:-cuda:0}" \
    TOXICITY_TRUTHFUL_SCORE_PENALTY="${TOXICITY_TRUTHFUL_SCORE_PENALTY:-0.0}" \
    bash "${TASK_SCRIPT}" \
    > "${LOG_FILE}" 2>&1
} || true

cat "${LOG_FILE}"
echo "Merge summary path: ${MERGE_SUMMARY_FILE}"
