#!/bin/bash
set -euo pipefail

if [[ -z "${BASH_VERSION:-}" ]]; then
  echo "Please run this script with bash." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

TASK="${TASK:-truth}"
MODEL_MODE="${MODEL_MODE:-auto}"
MODEL_PATH="${MODEL_PATH:-}"
BASE_MODEL="${BASE_MODEL:-}"
TARGET_LAYERS="${TARGET_LAYERS:--1}"
SUBSPACE_RANK="${SUBSPACE_RANK:-8}"
DEVICE="${DEVICE:-cuda:0}"
SUMMARY_PATH="${SUMMARY_PATH:-}"
RESULT_PREFIX="${RESULT_PREFIX:-}"
CHECKPOINT_NAME="${CHECKPOINT_NAME:-}"
TASK_OUTPUT_ROOT="${TASK_OUTPUT_ROOT:-}"

if [[ -z "${MODEL_PATH}" ]]; then
  echo "MODEL_PATH must be set." >&2
  exit 1
fi

case "${MODEL_MODE}" in
  auto)
    if [[ -f "${MODEL_PATH}/adapter_config.json" || -f "${MODEL_PATH}/adapter_model.safetensors" || -f "${MODEL_PATH}/adapter_model.bin" ]]; then
      MODEL_MODE="lora"
    else
      MODEL_MODE="base"
    fi
    ;;
  base|sft)
    MODEL_MODE="base"
    ;;
  lora)
    ;;
  *)
    echo "Unsupported MODEL_MODE=${MODEL_MODE}. Expected one of: auto base sft lora." >&2
    exit 1
    ;;
esac

if [[ "${MODEL_MODE}" == "lora" && -z "${BASE_MODEL}" ]]; then
  echo "BASE_MODEL must be set for MODEL_MODE=lora." >&2
  exit 1
fi

RUN_BASE_MODEL="${BASE_MODEL}"
RUN_LORA_WEIGHTS=""

if [[ "${MODEL_MODE}" == "base" ]]; then
  RUN_BASE_MODEL="${MODEL_PATH}"
else
  RUN_LORA_WEIGHTS="${MODEL_PATH}"
fi

echo "TASK=${TASK}"
echo "MODEL_MODE=${MODEL_MODE}"
echo "MODEL_PATH=${MODEL_PATH}"
echo "BASE_MODEL=${RUN_BASE_MODEL}"
echo "LORA_WEIGHTS=${RUN_LORA_WEIGHTS}"
echo "DEVICE=${DEVICE}"
echo "SUMMARY_PATH=${SUMMARY_PATH}"
echo "RESULT_PREFIX=${RESULT_PREFIX}"
echo "CHECKPOINT_NAME=${CHECKPOINT_NAME}"
echo "TASK_OUTPUT_ROOT=${TASK_OUTPUT_ROOT}"

exec env \
  TASK="${TASK}" \
  BASE_MODEL="${RUN_BASE_MODEL}" \
  LORA_WEIGHTS="${RUN_LORA_WEIGHTS}" \
  REFT_WEIGHTS="" \
  TARGET_LAYERS="${TARGET_LAYERS}" \
  SUBSPACE_RANK="${SUBSPACE_RANK}" \
  DEVICE="${DEVICE}" \
  SUMMARY_PATH="${SUMMARY_PATH}" \
  RESULT_PREFIX="${RESULT_PREFIX}" \
  CHECKPOINT_NAME="${CHECKPOINT_NAME}" \
  TASK_OUTPUT_ROOT="${TASK_OUTPUT_ROOT}" \
  PYTHON_BIN="${PYTHON_BIN:-/opt/conda/bin/python}" \
  DATASET="${DATASET:-}" \
  BATCH_SIZE="${BATCH_SIZE:-}" \
  POSITIONS="${POSITIONS:-}" \
  GREEDY_DECODING="${GREEDY_DECODING:-}" \
  PROMPT_TYPES="${PROMPT_TYPES:-}" \
  DATASET_FILE="${DATASET_FILE:-}" \
  ONLY_SHORT="${ONLY_SHORT:-}" \
  MAX_SAMPLES="${MAX_SAMPLES:-}" \
  N_GENERATIONS="${N_GENERATIONS:-}" \
  MAX_TOKENS="${MAX_TOKENS:-}" \
  TEMPERATURE="${TEMPERATURE:-}" \
  DATASETS="${DATASETS:-}" \
  PROMPTS="${PROMPTS:-}" \
  DATASET_ROOT="${DATASET_ROOT:-}" \
  RUN_ANALYSIS="${RUN_ANALYSIS:-}" \
  ANALYSIS_BATCH_SIZE="${ANALYSIS_BATCH_SIZE:-}" \
  DETOXIFY_MODEL="${DETOXIFY_MODEL:-}" \
  ANALYSIS_DEVICE="${ANALYSIS_DEVICE:-}" \
  ALLOW_ANALYSIS_FALLBACK="${ALLOW_ANALYSIS_FALLBACK:-0}" \
  TRUTH_DATASET="${TRUTH_DATASET:-}" \
  TRUTH_BATCH_SIZE="${TRUTH_BATCH_SIZE:-}" \
  TRUTH_POSITIONS="${TRUTH_POSITIONS:-}" \
  TRUTH_GREEDY_DECODING="${TRUTH_GREEDY_DECODING:-}" \
  BIAS_DATASET="${BIAS_DATASET:-}" \
  BIAS_BATCH_SIZE="${BIAS_BATCH_SIZE:-}" \
  BIAS_POSITIONS="${BIAS_POSITIONS:-}" \
  BIAS_GREEDY_DECODING="${BIAS_GREEDY_DECODING:-}" \
  ETHICS_BATCH_SIZE="${ETHICS_BATCH_SIZE:-}" \
  ETHICS_POSITIONS="${ETHICS_POSITIONS:-}" \
  ETHICS_GREEDY_DECODING="${ETHICS_GREEDY_DECODING:-}" \
  ETHICS_PROMPT_TYPES="${ETHICS_PROMPT_TYPES:-}" \
  ETHICS_DATASET_FILE="${ETHICS_DATASET_FILE:-}" \
  ETHICS_ONLY_SHORT="${ETHICS_ONLY_SHORT:-}" \
  ETHICS_MAX_SAMPLES="${ETHICS_MAX_SAMPLES:-}" \
  ETHICS_N_GENERATIONS="${ETHICS_N_GENERATIONS:-}" \
  ETHICS_MAX_TOKENS="${ETHICS_MAX_TOKENS:-}" \
  ETHICS_TEMPERATURE="${ETHICS_TEMPERATURE:-}" \
  TOXICITY_BATCH_SIZE="${TOXICITY_BATCH_SIZE:-}" \
  TOXICITY_POSITIONS="${TOXICITY_POSITIONS:-}" \
  TOXICITY_GREEDY_DECODING="${TOXICITY_GREEDY_DECODING:-}" \
  TOXICITY_DATASETS="${TOXICITY_DATASETS:-}" \
  TOXICITY_PROMPTS="${TOXICITY_PROMPTS:-}" \
  TOXICITY_DATASET_ROOT="${TOXICITY_DATASET_ROOT:-}" \
  TOXICITY_MAX_SAMPLES="${TOXICITY_MAX_SAMPLES:-}" \
  TOXICITY_N_GENERATIONS="${TOXICITY_N_GENERATIONS:-}" \
  TOXICITY_MAX_TOKENS="${TOXICITY_MAX_TOKENS:-}" \
  TOXICITY_TEMPERATURE="${TOXICITY_TEMPERATURE:-}" \
  TOXICITY_RUN_ANALYSIS="${TOXICITY_RUN_ANALYSIS:-}" \
  TOXICITY_ALLOW_ANALYSIS_FALLBACK="${TOXICITY_ALLOW_ANALYSIS_FALLBACK:-0}" \
  TOXICITY_ANALYSIS_BATCH_SIZE="${TOXICITY_ANALYSIS_BATCH_SIZE:-}" \
  TOXICITY_DETOXIFY_MODEL="${TOXICITY_DETOXIFY_MODEL:-}" \
  TOXICITY_ANALYSIS_DEVICE="${TOXICITY_ANALYSIS_DEVICE:-}" \
  bash "${SCRIPT_DIR}/evaluate_specialist_task.sh"
